//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmonogram
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Department : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        private int _departmentid;
        public int DepartmentId { get { return _departmentid; } set { _departmentid = value; OnPropertyChanged("DepartmentId");} }
    	private string _name;
        public string Name { get { return _name; } set { _name = value; OnPropertyChanged("Name");} }
    }
}
