//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmonogram
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Expedition : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        private int _expeditionid;
        public int ExpeditionId { get { return _expeditionid; } set { _expeditionid = value; OnPropertyChanged("ExpeditionId");} }
    	private int _orderid;
        public int OrderId { get { return _orderid; } set { _orderid = value; OnPropertyChanged("OrderId");} }
    	private string _expediceporadi;
        public string ExpedicePoradi { get { return _expediceporadi; } set { _expediceporadi = value; OnPropertyChanged("ExpedicePoradi");} }
    	private string _expediceauto;
        public string ExpediceAuto { get { return _expediceauto; } set { _expediceauto = value; OnPropertyChanged("ExpediceAuto");} }
    	private Nullable<System.DateTime> _expedicedatum;
        public Nullable<System.DateTime> ExpediceDatum { get { return _expedicedatum; } set { _expedicedatum = value; OnPropertyChanged("ExpediceDatum");} }
    	private string _doplnmat;
        public string DoplnMat { get { return _doplnmat; } set { _doplnmat = value; OnPropertyChanged("DoplnMat");} }
    	private string _kridlaksexpedovanych;
        public string KridlaKsExpedovanych { get { return _kridlaksexpedovanych; } set { _kridlaksexpedovanych = value; OnPropertyChanged("KridlaKsExpedovanych");} }
    	private string _zarubneksexpedovanych;
        public string ZarubneKsExpedovanych { get { return _zarubneksexpedovanych; } set { _zarubneksexpedovanych = value; OnPropertyChanged("ZarubneKsExpedovanych");} }
    	private Nullable<int> _expeditedsortnr;
        public Nullable<int> ExpeditedSortNr { get { return _expeditedsortnr; } set { _expeditedsortnr = value; OnPropertyChanged("ExpeditedSortNr");} }
    	private string _kridlakszbyvaexpedovat;
        public string KridlaKsZbyvaExpedovat { get { return _kridlakszbyvaexpedovat; } set { _kridlakszbyvaexpedovat = value; OnPropertyChanged("KridlaKsZbyvaExpedovat");} }
    	private string _zarubnekszbyvaexpedovat;
        public string ZarubneKsZbyvaExpedovat { get { return _zarubnekszbyvaexpedovat; } set { _zarubnekszbyvaexpedovat = value; OnPropertyChanged("ZarubneKsZbyvaExpedovat");} }
    	private string _exepdicecolor;
        public string ExepdiceColor { get { return _exepdicecolor; } set { _exepdicecolor = value; OnPropertyChanged("ExepdiceColor");} }
    	private string _autocolor;
        public string AutoColor { get { return _autocolor; } set { _autocolor = value; OnPropertyChanged("AutoColor");} }
    
        public virtual Order Order { get; set; }
    }
}
