//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmonogram
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order : INotifyPropertyChanged
    {
    
    	public event PropertyChangedEventHandler PropertyChanged;
    	protected virtual void OnPropertyChanged(string propertyName)
    	{
    			PropertyChangedEventHandler handler = PropertyChanged;
    			if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
    	}
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Expeditions = new HashSet<Expedition>();
        }
    
    	private int _orderid;
        public int OrderId { get { return _orderid; } set { _orderid = value; OnPropertyChanged("OrderId");} }
    	private Nullable<int> _sortnr;
        public Nullable<int> SortNr { get { return _sortnr; } set { _sortnr = value; OnPropertyChanged("SortNr");} }
    	private bool _notblank;
        public bool NotBlank { get { return _notblank; } set { _notblank = value; OnPropertyChanged("NotBlank");} }
    	private bool _isinproccess;
        public bool IsInProccess { get { return _isinproccess; } set { _isinproccess = value; OnPropertyChanged("IsInProccess");} }
    	private Nullable<int> _department;
        public Nullable<int> Department { get { return _department; } set { _department = value; OnPropertyChanged("Department");} }
    	private string _archivedby;
        public string ArchivedBy { get { return _archivedby; } set { _archivedby = value; OnPropertyChanged("ArchivedBy");} }
    	private Nullable<System.DateTime> _archiveddate;
        public Nullable<System.DateTime> ArchivedDate { get { return _archiveddate; } set { _archiveddate = value; OnPropertyChanged("ArchivedDate");} }
    	private bool _isarchived;
        public bool IsArchived { get { return _isarchived; } set { _isarchived = value; OnPropertyChanged("IsArchived");} }
    	private bool _isdeleted;
        public bool IsDeleted { get { return _isdeleted; } set { _isdeleted = value; OnPropertyChanged("IsDeleted");} }
    	private Nullable<System.DateTime> _deleteddate;
        public Nullable<System.DateTime> DeletedDate { get { return _deleteddate; } set { _deleteddate = value; OnPropertyChanged("DeletedDate");} }
    	private string _deletedby;
        public string DeletedBy { get { return _deletedby; } set { _deletedby = value; OnPropertyChanged("DeletedBy");} }
    	private string _color;
        public string Color { get { return _color; } set { _color = value; OnPropertyChanged("Color");} }
    	private string _pripravac;
        public string PripravaC { get { return _pripravac; } set { _pripravac = value; OnPropertyChanged("PripravaC");} }
    	private string _priprava;
        public string Priprava { get { return _priprava; } set { _priprava = value; OnPropertyChanged("Priprava");} }
    	private string _oblozkyc;
        public string OblozkyC { get { return _oblozkyc; } set { _oblozkyc = value; OnPropertyChanged("OblozkyC");} }
    	private string _oblozky;
        public string Oblozky { get { return _oblozky; } set { _oblozky = value; OnPropertyChanged("Oblozky");} }
    	private string _stredovec;
        public string StredoveC { get { return _stredovec; } set { _stredovec = value; OnPropertyChanged("StredoveC");} }
    	private string _stredove;
        public string Stredove { get { return _stredove; } set { _stredove = value; OnPropertyChanged("Stredove");} }
    	private string _ramecekc;
        public string RamecekC { get { return _ramecekc; } set { _ramecekc = value; OnPropertyChanged("RamecekC");} }
    	private string _ramecek;
        public string Ramecek { get { return _ramecek; } set { _ramecek = value; OnPropertyChanged("Ramecek");} }
    	private string _klapackac;
        public string KlapackaC { get { return _klapackac; } set { _klapackac = value; OnPropertyChanged("KlapackaC");} }
    	private string _klapacka;
        public string Klapacka { get { return _klapacka; } set { _klapacka = value; OnPropertyChanged("Klapacka");} }
    	private string _posuvc;
        public string PosuvC { get { return _posuvc; } set { _posuvc = value; OnPropertyChanged("PosuvC");} }
    	private string _posuv;
        public string Posuv { get { return _posuv; } set { _posuv = value; OnPropertyChanged("Posuv");} }
    	private string _dverec;
        public string DvereC { get { return _dverec; } set { _dverec = value; OnPropertyChanged("DvereC");} }
    	private string _dvere;
        public string Dvere { get { return _dvere; } set { _dvere = value; OnPropertyChanged("Dvere");} }
    	private string _dokoncenic;
        public string DokonceniC { get { return _dokoncenic; } set { _dokoncenic = value; OnPropertyChanged("DokonceniC");} }
    	private string _dokonceni;
        public string Dokonceni { get { return _dokonceni; } set { _dokonceni = value; OnPropertyChanged("Dokonceni");} }
    	private string _kompletacec;
        public string KompletaceC { get { return _kompletacec; } set { _kompletacec = value; OnPropertyChanged("KompletaceC");} }
    	private string _kompletace;
        public string Kompletace { get { return _kompletace; } set { _kompletace = value; OnPropertyChanged("Kompletace");} }
    	private string _skladc;
        public string SkladC { get { return _skladc; } set { _skladc = value; OnPropertyChanged("SkladC");} }
    	private string _sklad;
        public string Sklad { get { return _sklad; } set { _sklad = value; OnPropertyChanged("Sklad");} }
    	private Nullable<System.DateTime> _zahajenidatum;
        public Nullable<System.DateTime> ZahajeniDatum { get { return _zahajenidatum; } set { _zahajenidatum = value; OnPropertyChanged("ZahajeniDatum");} }
    	private string _technik;
        public string Technik { get { return _technik; } set { _technik = value; OnPropertyChanged("Technik");} }
    	private string _zakazka;
        public string Zakazka { get { return _zakazka; } set { _zakazka = value; OnPropertyChanged("Zakazka");} }
    	private string _material;
        public string Material { get { return _material; } set { _material = value; OnPropertyChanged("Material");} }
    	private string _zakazkacolor;
        public string ZakazkaColor { get { return _zakazkacolor; } set { _zakazkacolor = value; OnPropertyChanged("ZakazkaColor");} }
    	private string _materialcolor;
        public string MaterialColor { get { return _materialcolor; } set { _materialcolor = value; OnPropertyChanged("MaterialColor");} }
    	private string _zakazkanr;
        public string ZakazkaNr { get { return _zakazkanr; } set { _zakazkanr = value; OnPropertyChanged("ZakazkaNr");} }
    	private string _vyrobninr;
        public string VyrobniNr { get { return _vyrobninr; } set { _vyrobninr = value; OnPropertyChanged("VyrobniNr");} }
    	private string _kridlatext;
        public string KridlaText { get { return _kridlatext; } set { _kridlatext = value; OnPropertyChanged("KridlaText");} }
    	private string _kridlaksexpedovanych;
        public string KridlaKsExpedovanych { get { return _kridlaksexpedovanych; } set { _kridlaksexpedovanych = value; OnPropertyChanged("KridlaKsExpedovanych");} }
    	private string _kridlaks;
        public string KridlaKs { get { return _kridlaks; } set { _kridlaks = value; OnPropertyChanged("KridlaKs");} }
    	private string _zarubnetext;
        public string ZarubneText { get { return _zarubnetext; } set { _zarubnetext = value; OnPropertyChanged("ZarubneText");} }
    	private string _zarubneksexpedovanych;
        public string ZarubneKsExpedovanych { get { return _zarubneksexpedovanych; } set { _zarubneksexpedovanych = value; OnPropertyChanged("ZarubneKsExpedovanych");} }
    	private string _zarubneks;
        public string ZarubneKs { get { return _zarubneks; } set { _zarubneks = value; OnPropertyChanged("ZarubneKs");} }
    	private string _typzarubne;
        public string TypZarubne { get { return _typzarubne; } set { _typzarubne = value; OnPropertyChanged("TypZarubne");} }
    	private string _dokumentace;
        public string Dokumentace { get { return _dokumentace; } set { _dokumentace = value; OnPropertyChanged("Dokumentace");} }
    	private string _dokumentacec;
        public string DokumentaceC { get { return _dokumentacec; } set { _dokumentacec = value; OnPropertyChanged("DokumentaceC");} }
    	private string _indoca;
        public string InDoca { get { return _indoca; } set { _indoca = value; OnPropertyChanged("InDoca");} }
    	private string _indocac;
        public string InDocaC { get { return _indocac; } set { _indocac = value; OnPropertyChanged("InDocaC");} }
    	private string _docurl;
        public string DocUrl { get { return _docurl; } set { _docurl = value; OnPropertyChanged("DocUrl");} }
    	private string _obalovatoblozkyc;
        public string ObalovatOblozkyC { get { return _obalovatoblozkyc; } set { _obalovatoblozkyc = value; OnPropertyChanged("ObalovatOblozkyC");} }
    	private string _obalovatoblozky;
        public string ObalovatOblozky { get { return _obalovatoblozky; } set { _obalovatoblozky = value; OnPropertyChanged("ObalovatOblozky");} }
    	private string _rezatoblozkyc;
        public string RezatOblozkyC { get { return _rezatoblozkyc; } set { _rezatoblozkyc = value; OnPropertyChanged("RezatOblozkyC");} }
    	private string _rezatoblozky;
        public string RezatOblozky { get { return _rezatoblozky; } set { _rezatoblozky = value; OnPropertyChanged("RezatOblozky");} }
    	private string _cncoblozkyc;
        public string CncOblozkyC { get { return _cncoblozkyc; } set { _cncoblozkyc = value; OnPropertyChanged("CncOblozkyC");} }
    	private string _cncoblozky;
        public string CncOblozky { get { return _cncoblozky; } set { _cncoblozky = value; OnPropertyChanged("CncOblozky");} }
    	private string _centrumstredovec;
        public string CentrumStredoveC { get { return _centrumstredovec; } set { _centrumstredovec = value; OnPropertyChanged("CentrumStredoveC");} }
    	private string _centrumstredove;
        public string CentrumStredove { get { return _centrumstredove; } set { _centrumstredove = value; OnPropertyChanged("CentrumStredove");} }
    	private string _lisstredovec;
        public string LisStredoveC { get { return _lisstredovec; } set { _lisstredovec = value; OnPropertyChanged("LisStredoveC");} }
    	private string _lisstredove;
        public string LisStredove { get { return _lisstredove; } set { _lisstredove = value; OnPropertyChanged("LisStredove");} }
    	private string _olepovanistredovec;
        public string OlepovaniStredoveC { get { return _olepovanistredovec; } set { _olepovanistredovec = value; OnPropertyChanged("OlepovaniStredoveC");} }
    	private string _olepovanistredove;
        public string OlepovaniStredove { get { return _olepovanistredove; } set { _olepovanistredove = value; OnPropertyChanged("OlepovaniStredove");} }
    	private string _frezovanistredovec;
        public string FrezovaniStredoveC { get { return _frezovanistredovec; } set { _frezovanistredovec = value; OnPropertyChanged("FrezovaniStredoveC");} }
    	private string _frezovanistredove;
        public string FrezovaniStredove { get { return _frezovanistredove; } set { _frezovanistredove = value; OnPropertyChanged("FrezovaniStredove");} }
    	private string _typramecekc;
        public string TypRamecekC { get { return _typramecekc; } set { _typramecekc = value; OnPropertyChanged("TypRamecekC");} }
    	private string _typramecek;
        public string TypRamecek { get { return _typramecek; } set { _typramecek = value; OnPropertyChanged("TypRamecek");} }
    	private string _obalovaniramecekc;
        public string ObalovaniRamecekC { get { return _obalovaniramecekc; } set { _obalovaniramecekc = value; OnPropertyChanged("ObalovaniRamecekC");} }
    	private string _obalovaniramecek;
        public string ObalovaniRamecek { get { return _obalovaniramecek; } set { _obalovaniramecek = value; OnPropertyChanged("ObalovaniRamecek");} }
    	private string _rezaniramecekc;
        public string RezaniRamecekC { get { return _rezaniramecekc; } set { _rezaniramecekc = value; OnPropertyChanged("RezaniRamecekC");} }
    	private string _rezaniramecek;
        public string RezaniRamecek { get { return _rezaniramecek; } set { _rezaniramecek = value; OnPropertyChanged("RezaniRamecek");} }
    	private string _obalovaniklapackac;
        public string ObalovaniKlapackaC { get { return _obalovaniklapackac; } set { _obalovaniklapackac = value; OnPropertyChanged("ObalovaniKlapackaC");} }
    	private string _obalovaniklapacka;
        public string ObalovaniKlapacka { get { return _obalovaniklapacka; } set { _obalovaniklapacka = value; OnPropertyChanged("ObalovaniKlapacka");} }
    	private string _rezaniklapackac;
        public string RezaniKlapackaC { get { return _rezaniklapackac; } set { _rezaniklapackac = value; OnPropertyChanged("RezaniKlapackaC");} }
    	private string _rezaniklapacka;
        public string RezaniKlapacka { get { return _rezaniklapacka; } set { _rezaniklapacka = value; OnPropertyChanged("RezaniKlapacka");} }
    	private string _hranolposuvc;
        public string HranolPosuvC { get { return _hranolposuvc; } set { _hranolposuvc = value; OnPropertyChanged("HranolPosuvC");} }
    	private string _hranolposuv;
        public string HranolPosuv { get { return _hranolposuv; } set { _hranolposuv = value; OnPropertyChanged("HranolPosuv");} }
    	private string _garnyzposuvc;
        public string GarnyzPosuvC { get { return _garnyzposuvc; } set { _garnyzposuvc = value; OnPropertyChanged("GarnyzPosuvC");} }
    	private string _garnyzposuv;
        public string GarnyzPosuv { get { return _garnyzposuv; } set { _garnyzposuv = value; OnPropertyChanged("GarnyzPosuv");} }
    	private string _dorazovaposuvc;
        public string DorazovaPosuvC { get { return _dorazovaposuvc; } set { _dorazovaposuvc = value; OnPropertyChanged("DorazovaPosuvC");} }
    	private string _dorazovaposuv;
        public string DorazovaPosuv { get { return _dorazovaposuv; } set { _dorazovaposuv = value; OnPropertyChanged("DorazovaPosuv");} }
    	private string _centrumdverec;
        public string CentrumDvereC { get { return _centrumdverec; } set { _centrumdverec = value; OnPropertyChanged("CentrumDvereC");} }
    	private string _centrumdvere;
        public string CentrumDvere { get { return _centrumdvere; } set { _centrumdvere = value; OnPropertyChanged("CentrumDvere");} }
    	private string _korpusydverec;
        public string KorpusyDvereC { get { return _korpusydverec; } set { _korpusydverec = value; OnPropertyChanged("KorpusyDvereC");} }
    	private string _korpusydvere;
        public string KorpusyDvere { get { return _korpusydvere; } set { _korpusydvere = value; OnPropertyChanged("KorpusyDvere");} }
    	private string _sesazenkydverec;
        public string SesazenkyDvereC { get { return _sesazenkydverec; } set { _sesazenkydverec = value; OnPropertyChanged("SesazenkyDvereC");} }
    	private string _sesazenkydvere;
        public string SesazenkyDvere { get { return _sesazenkydvere; } set { _sesazenkydvere = value; OnPropertyChanged("SesazenkyDvere");} }
    	private string _lisdverec;
        public string LisDvereC { get { return _lisdverec; } set { _lisdverec = value; OnPropertyChanged("LisDvereC");} }
    	private string _lisdvere;
        public string LisDvere { get { return _lisdvere; } set { _lisdvere = value; OnPropertyChanged("LisDvere");} }
    	private string _formatkadverec;
        public string FormatkaDvereC { get { return _formatkadverec; } set { _formatkadverec = value; OnPropertyChanged("FormatkaDvereC");} }
    	private string _formatkadvere;
        public string FormatkaDvere { get { return _formatkadvere; } set { _formatkadvere = value; OnPropertyChanged("FormatkaDvere");} }
    	private string _olepovackadverec;
        public string OlepovackaDvereC { get { return _olepovackadverec; } set { _olepovackadverec = value; OnPropertyChanged("OlepovackaDvereC");} }
    	private string _olepovackadvere;
        public string OlepovackaDvere { get { return _olepovackadvere; } set { _olepovackadvere = value; OnPropertyChanged("OlepovackaDvere");} }
    	private string _cncdverec;
        public string CncDvereC { get { return _cncdverec; } set { _cncdverec = value; OnPropertyChanged("CncDvereC");} }
    	private string _cncdvere;
        public string CncDvere { get { return _cncdvere; } set { _cncdvere = value; OnPropertyChanged("CncDvere");} }
    	private string _pgmdverec;
        public string PgmDvereC { get { return _pgmdverec; } set { _pgmdverec = value; OnPropertyChanged("PgmDvereC");} }
    	private string _pgmdvere;
        public string PgmDvere { get { return _pgmdvere; } set { _pgmdvere = value; OnPropertyChanged("PgmDvere");} }
    	private string _brousenidyhadokoncenic;
        public string BrouseniDyhaDokonceniC { get { return _brousenidyhadokoncenic; } set { _brousenidyhadokoncenic = value; OnPropertyChanged("BrouseniDyhaDokonceniC");} }
    	private string _brousenidyhadokonceni;
        public string BrouseniDyhaDokonceni { get { return _brousenidyhadokonceni; } set { _brousenidyhadokonceni = value; OnPropertyChanged("BrouseniDyhaDokonceni");} }
    	private string _zakladdokoncenic;
        public string ZakladDokonceniC { get { return _zakladdokoncenic; } set { _zakladdokoncenic = value; OnPropertyChanged("ZakladDokonceniC");} }
    	private string _zakladdokonceni;
        public string ZakladDokonceni { get { return _zakladdokonceni; } set { _zakladdokonceni = value; OnPropertyChanged("ZakladDokonceni");} }
    	private string _brousenizakladdokoncenic;
        public string BrouseniZakladDokonceniC { get { return _brousenizakladdokoncenic; } set { _brousenizakladdokoncenic = value; OnPropertyChanged("BrouseniZakladDokonceniC");} }
    	private string _brousenizakladdokonceni;
        public string BrouseniZakladDokonceni { get { return _brousenizakladdokonceni; } set { _brousenizakladdokonceni = value; OnPropertyChanged("BrouseniZakladDokonceni");} }
    	private string _vrchdokoncenic;
        public string VrchDokonceniC { get { return _vrchdokoncenic; } set { _vrchdokoncenic = value; OnPropertyChanged("VrchDokonceniC");} }
    	private string _vrchdokonceni;
        public string VrchDokonceni { get { return _vrchdokonceni; } set { _vrchdokonceni = value; OnPropertyChanged("VrchDokonceni");} }
    	private string _dverekompletacec;
        public string DvereKompletaceC { get { return _dverekompletacec; } set { _dverekompletacec = value; OnPropertyChanged("DvereKompletaceC");} }
    	private string _dverekompletace;
        public string DvereKompletace { get { return _dverekompletace; } set { _dverekompletace = value; OnPropertyChanged("DvereKompletace");} }
    	private string _zarubenkompletacec;
        public string ZarubenKompletaceC { get { return _zarubenkompletacec; } set { _zarubenkompletacec = value; OnPropertyChanged("ZarubenKompletaceC");} }
    	private string _zarubenkompletace;
        public string ZarubenKompletace { get { return _zarubenkompletace; } set { _zarubenkompletace = value; OnPropertyChanged("ZarubenKompletace");} }
    	private string _kovaniskladc;
        public string KovaniSkladC { get { return _kovaniskladc; } set { _kovaniskladc = value; OnPropertyChanged("KovaniSkladC");} }
    	private string _kovanisklad;
        public string KovaniSklad { get { return _kovanisklad; } set { _kovanisklad = value; OnPropertyChanged("KovaniSklad");} }
    	private string _skloskladc;
        public string SkloSkladC { get { return _skloskladc; } set { _skloskladc = value; OnPropertyChanged("SkloSkladC");} }
    	private string _sklosklad;
        public string SkloSklad { get { return _sklosklad; } set { _sklosklad = value; OnPropertyChanged("SkloSklad");} }
    	private string _pripravazarc;
        public string PripravaZarC { get { return _pripravazarc; } set { _pripravazarc = value; OnPropertyChanged("PripravaZarC");} }
    	private string _pripravazar;
        public string PripravaZar { get { return _pripravazar; } set { _pripravazar = value; OnPropertyChanged("PripravaZar");} }
    	private string _dokumentpripravazarc;
        public string DokumentPripravaZarC { get { return _dokumentpripravazarc; } set { _dokumentpripravazarc = value; OnPropertyChanged("DokumentPripravaZarC");} }
    	private string _dokumentpripravazar;
        public string DokumentPripravaZar { get { return _dokumentpripravazar; } set { _dokumentpripravazar = value; OnPropertyChanged("DokumentPripravaZar");} }
    	private string _indocapripravazarc;
        public string InDocaPripravaZarC { get { return _indocapripravazarc; } set { _indocapripravazarc = value; OnPropertyChanged("InDocaPripravaZarC");} }
    	private string _indocapripravazar;
        public string InDocaPripravaZar { get { return _indocapripravazar; } set { _indocapripravazar = value; OnPropertyChanged("InDocaPripravaZar");} }
    	private string _laserzarc;
        public string LaserZarC { get { return _laserzarc; } set { _laserzarc = value; OnPropertyChanged("LaserZarC");} }
    	private string _laserzar;
        public string LaserZar { get { return _laserzar; } set { _laserzar = value; OnPropertyChanged("LaserZar");} }
    	private string _pohlaserzarc;
        public string PohLaserZarC { get { return _pohlaserzarc; } set { _pohlaserzarc = value; OnPropertyChanged("PohLaserZarC");} }
    	private string _pohlaserzar;
        public string PohLaserZar { get { return _pohlaserzar; } set { _pohlaserzar = value; OnPropertyChanged("PohLaserZar");} }
    	private string _nepohlaserzarc;
        public string NepohLaserZarC { get { return _nepohlaserzarc; } set { _nepohlaserzarc = value; OnPropertyChanged("NepohLaserZarC");} }
    	private string _nepohlaserzar;
        public string NepohLaserZar { get { return _nepohlaserzar; } set { _nepohlaserzar = value; OnPropertyChanged("NepohLaserZar");} }
    	private string _pouteclaserzarc;
        public string PoutecLaserZarC { get { return _pouteclaserzarc; } set { _pouteclaserzarc = value; OnPropertyChanged("PoutecLaserZarC");} }
    	private string _pouteclaserzar;
        public string PoutecLaserZar { get { return _pouteclaserzar; } set { _pouteclaserzar = value; OnPropertyChanged("PoutecLaserZar");} }
    	private string _nuzkyzarc;
        public string NuzkyZarC { get { return _nuzkyzarc; } set { _nuzkyzarc = value; OnPropertyChanged("NuzkyZarC");} }
    	private string _nuzkyzar;
        public string NuzkyZar { get { return _nuzkyzar; } set { _nuzkyzar = value; OnPropertyChanged("NuzkyZar");} }
    	private string _splnenonuzkyzarc;
        public string SplnenoNuzkyZarC { get { return _splnenonuzkyzarc; } set { _splnenonuzkyzarc = value; OnPropertyChanged("SplnenoNuzkyZarC");} }
    	private string _splnenonuzkyzar;
        public string SplnenoNuzkyZar { get { return _splnenonuzkyzar; } set { _splnenonuzkyzar = value; OnPropertyChanged("SplnenoNuzkyZar");} }
    	private string _ohybackazarc;
        public string OhybackaZarC { get { return _ohybackazarc; } set { _ohybackazarc = value; OnPropertyChanged("OhybackaZarC");} }
    	private string _ohybackazar;
        public string OhybackaZar { get { return _ohybackazar; } set { _ohybackazar = value; OnPropertyChanged("OhybackaZar");} }
    	private string _pohohybackazarc;
        public string PohOhybackaZarC { get { return _pohohybackazarc; } set { _pohohybackazarc = value; OnPropertyChanged("PohOhybackaZarC");} }
    	private string _pohohybackazar;
        public string PohOhybackaZar { get { return _pohohybackazar; } set { _pohohybackazar = value; OnPropertyChanged("PohOhybackaZar");} }
    	private string _nepohohybackazarc;
        public string NepohOhybackaZarC { get { return _nepohohybackazarc; } set { _nepohohybackazarc = value; OnPropertyChanged("NepohOhybackaZarC");} }
    	private string _nepohohybackazar;
        public string NepohOhybackaZar { get { return _nepohohybackazar; } set { _nepohohybackazar = value; OnPropertyChanged("NepohOhybackaZar");} }
    	private string _poutecohybackazarc;
        public string PoutecOhybackaZarC { get { return _poutecohybackazarc; } set { _poutecohybackazarc = value; OnPropertyChanged("PoutecOhybackaZarC");} }
    	private string _poutecohybackazar;
        public string PoutecOhybackaZar { get { return _poutecohybackazar; } set { _poutecohybackazar = value; OnPropertyChanged("PoutecOhybackaZar");} }
    	private string _pilazarc;
        public string PilaZarC { get { return _pilazarc; } set { _pilazarc = value; OnPropertyChanged("PilaZarC");} }
    	private string _pilazar;
        public string PilaZar { get { return _pilazar; } set { _pilazar = value; OnPropertyChanged("PilaZar");} }
    	private string _pohpilazarc;
        public string PohPilaZarC { get { return _pohpilazarc; } set { _pohpilazarc = value; OnPropertyChanged("PohPilaZarC");} }
    	private string _pohpilazar;
        public string PohPilaZar { get { return _pohpilazar; } set { _pohpilazar = value; OnPropertyChanged("PohPilaZar");} }
    	private string _nepohpilazarc;
        public string NepohPilaZarC { get { return _nepohpilazarc; } set { _nepohpilazarc = value; OnPropertyChanged("NepohPilaZarC");} }
    	private string _nepohpilazar;
        public string NepohPilaZar { get { return _nepohpilazar; } set { _nepohpilazar = value; OnPropertyChanged("NepohPilaZar");} }
    	private string _vyrazeckazarc;
        public string VyrazeckaZarC { get { return _vyrazeckazarc; } set { _vyrazeckazarc = value; OnPropertyChanged("VyrazeckaZarC");} }
    	private string _vyrazeckazar;
        public string VyrazeckaZar { get { return _vyrazeckazar; } set { _vyrazeckazar = value; OnPropertyChanged("VyrazeckaZar");} }
    	private string _splnenovyrazeckazarc;
        public string SplnenoVyrazeckaZarC { get { return _splnenovyrazeckazarc; } set { _splnenovyrazeckazarc = value; OnPropertyChanged("SplnenoVyrazeckaZarC");} }
    	private string _splnenovyrazeckazar;
        public string SplnenoVyrazeckaZar { get { return _splnenovyrazeckazar; } set { _splnenovyrazeckazar = value; OnPropertyChanged("SplnenoVyrazeckaZar");} }
    	private string _bodovanizarc;
        public string BodovaniZarC { get { return _bodovanizarc; } set { _bodovanizarc = value; OnPropertyChanged("BodovaniZarC");} }
    	private string _bodovanizar;
        public string BodovaniZar { get { return _bodovanizar; } set { _bodovanizar = value; OnPropertyChanged("BodovaniZar");} }
    	private string _splnenobodovanizarc;
        public string SplnenoBodovaniZarC { get { return _splnenobodovanizarc; } set { _splnenobodovanizarc = value; OnPropertyChanged("SplnenoBodovaniZarC");} }
    	private string _splnenobodovanizar;
        public string SplnenoBodovaniZar { get { return _splnenobodovanizar; } set { _splnenobodovanizar = value; OnPropertyChanged("SplnenoBodovaniZar");} }
    	private string _svarovanizarc;
        public string SvarovaniZarC { get { return _svarovanizarc; } set { _svarovanizarc = value; OnPropertyChanged("SvarovaniZarC");} }
    	private string _svarovanizar;
        public string SvarovaniZar { get { return _svarovanizar; } set { _svarovanizar = value; OnPropertyChanged("SvarovaniZar");} }
    	private string _splnenosvarovanizarc;
        public string SplnenoSvarovaniZarC { get { return _splnenosvarovanizarc; } set { _splnenosvarovanizarc = value; OnPropertyChanged("SplnenoSvarovaniZarC");} }
    	private string _splnenosvarovanizar;
        public string SplnenoSvarovaniZar { get { return _splnenosvarovanizar; } set { _splnenosvarovanizar = value; OnPropertyChanged("SplnenoSvarovaniZar");} }
    	private string _brousenizarc;
        public string BrouseniZarC { get { return _brousenizarc; } set { _brousenizarc = value; OnPropertyChanged("BrouseniZarC");} }
    	private string _brousenizar;
        public string BrouseniZar { get { return _brousenizar; } set { _brousenizar = value; OnPropertyChanged("BrouseniZar");} }
    	private string _splnenobrousenizarc;
        public string SplnenoBrouseniZarC { get { return _splnenobrousenizarc; } set { _splnenobrousenizarc = value; OnPropertyChanged("SplnenoBrouseniZarC");} }
    	private string _splnenobrousenizar;
        public string SplnenoBrouseniZar { get { return _splnenobrousenizar; } set { _splnenobrousenizar = value; OnPropertyChanged("SplnenoBrouseniZar");} }
    	private string _strikarnazarc;
        public string StrikarnaZarC { get { return _strikarnazarc; } set { _strikarnazarc = value; OnPropertyChanged("StrikarnaZarC");} }
    	private string _strikarnazar;
        public string StrikarnaZar { get { return _strikarnazar; } set { _strikarnazar = value; OnPropertyChanged("StrikarnaZar");} }
    	private string _splnenostrikarnazarc;
        public string SplnenoStrikarnaZarC { get { return _splnenostrikarnazarc; } set { _splnenostrikarnazarc = value; OnPropertyChanged("SplnenoStrikarnaZarC");} }
    	private string _splnenostrikarnazar;
        public string SplnenoStrikarnaZar { get { return _splnenostrikarnazar; } set { _splnenostrikarnazar = value; OnPropertyChanged("SplnenoStrikarnaZar");} }
    	private string _rameckyzarc;
        public string RameckyZarC { get { return _rameckyzarc; } set { _rameckyzarc = value; OnPropertyChanged("RameckyZarC");} }
    	private string _rameckyzar;
        public string RameckyZar { get { return _rameckyzar; } set { _rameckyzar = value; OnPropertyChanged("RameckyZar");} }
    	private string _narezrameckyzarc;
        public string NarezRameckyZarC { get { return _narezrameckyzarc; } set { _narezrameckyzarc = value; OnPropertyChanged("NarezRameckyZarC");} }
    	private string _narezrameckyzar;
        public string NarezRameckyZar { get { return _narezrameckyzar; } set { _narezrameckyzar = value; OnPropertyChanged("NarezRameckyZar");} }
    	private string _frezrameckyzarc;
        public string FrezRameckyZarC { get { return _frezrameckyzarc; } set { _frezrameckyzarc = value; OnPropertyChanged("FrezRameckyZarC");} }
    	private string _frezrameckyzar;
        public string FrezRameckyZar { get { return _frezrameckyzar; } set { _frezrameckyzar = value; OnPropertyChanged("FrezRameckyZar");} }
    	private string _svarrameckyzarc;
        public string SvarRameckyZarC { get { return _svarrameckyzarc; } set { _svarrameckyzarc = value; OnPropertyChanged("SvarRameckyZarC");} }
    	private string _svarrameckyzar;
        public string SvarRameckyZar { get { return _svarrameckyzar; } set { _svarrameckyzar = value; OnPropertyChanged("SvarRameckyZar");} }
    	private string _strirameckyzarc;
        public string StriRameckyZarC { get { return _strirameckyzarc; } set { _strirameckyzarc = value; OnPropertyChanged("StriRameckyZarC");} }
    	private string _strirameckyzar;
        public string StriRameckyZar { get { return _strirameckyzar; } set { _strirameckyzar = value; OnPropertyChanged("StriRameckyZar");} }
    	private string _kompletacezarc;
        public string KompletaceZarC { get { return _kompletacezarc; } set { _kompletacezarc = value; OnPropertyChanged("KompletaceZarC");} }
    	private string _kompletacezar;
        public string KompletaceZar { get { return _kompletacezar; } set { _kompletacezar = value; OnPropertyChanged("KompletaceZar");} }
    	private string _splnenokompletacezarc;
        public string SplnenoKompletaceZarC { get { return _splnenokompletacezarc; } set { _splnenokompletacezarc = value; OnPropertyChanged("SplnenoKompletaceZarC");} }
    	private string _splnenokompletacezar;
        public string SplnenoKompletaceZar { get { return _splnenokompletacezar; } set { _splnenokompletacezar = value; OnPropertyChanged("SplnenoKompletaceZar");} }
    	private string _skladzarc;
        public string SkladZarC { get { return _skladzarc; } set { _skladzarc = value; OnPropertyChanged("SkladZarC");} }
    	private string _skladzar;
        public string SkladZar { get { return _skladzar; } set { _skladzar = value; OnPropertyChanged("SkladZar");} }
    	private string _plechskladzarc;
        public string PlechSkladZarC { get { return _plechskladzarc; } set { _plechskladzarc = value; OnPropertyChanged("PlechSkladZarC");} }
    	private string _plechskladzar;
        public string PlechSkladZar { get { return _plechskladzar; } set { _plechskladzar = value; OnPropertyChanged("PlechSkladZar");} }
    	private string _barvaskladzarc;
        public string BarvaSkladZarC { get { return _barvaskladzarc; } set { _barvaskladzarc = value; OnPropertyChanged("BarvaSkladZarC");} }
    	private string _barvaskladzar;
        public string BarvaSkladZar { get { return _barvaskladzar; } set { _barvaskladzar = value; OnPropertyChanged("BarvaSkladZar");} }
    	private string _kovaniskladzarc;
        public string KovaniSkladZarC { get { return _kovaniskladzarc; } set { _kovaniskladzarc = value; OnPropertyChanged("KovaniSkladZarC");} }
    	private string _kovaniskladzar;
        public string KovaniSkladZar { get { return _kovaniskladzar; } set { _kovaniskladzar = value; OnPropertyChanged("KovaniSkladZar");} }
    	private string _skloskladzarc;
        public string SkloSkladZarC { get { return _skloskladzarc; } set { _skloskladzarc = value; OnPropertyChanged("SkloSkladZarC");} }
    	private string _skloskladzar;
        public string SkloSkladZar { get { return _skloskladzar; } set { _skloskladzar = value; OnPropertyChanged("SkloSkladZar");} }
    	private string _pripravakridc;
        public string PripravaKridC { get { return _pripravakridc; } set { _pripravakridc = value; OnPropertyChanged("PripravaKridC");} }
    	private string _pripravakrid;
        public string PripravaKrid { get { return _pripravakrid; } set { _pripravakrid = value; OnPropertyChanged("PripravaKrid");} }
    	private string _dokumentpripravakridc;
        public string DokumentPripravaKridC { get { return _dokumentpripravakridc; } set { _dokumentpripravakridc = value; OnPropertyChanged("DokumentPripravaKridC");} }
    	private string _dokumentpripravakrid;
        public string DokumentPripravaKrid { get { return _dokumentpripravakrid; } set { _dokumentpripravakrid = value; OnPropertyChanged("DokumentPripravaKrid");} }
    	private string _indocapripravakridc;
        public string IndocaPripravaKridC { get { return _indocapripravakridc; } set { _indocapripravakridc = value; OnPropertyChanged("IndocaPripravaKridC");} }
    	private string _indocapripravakrid;
        public string IndocaPripravaKrid { get { return _indocapripravakrid; } set { _indocapripravakrid = value; OnPropertyChanged("IndocaPripravaKrid");} }
    	private string _laserkridc;
        public string LaserKridC { get { return _laserkridc; } set { _laserkridc = value; OnPropertyChanged("LaserKridC");} }
    	private string _laserkrid;
        public string LaserKrid { get { return _laserkrid; } set { _laserkrid = value; OnPropertyChanged("LaserKrid");} }
    	private string _pohlaserkridc;
        public string PohLaserKridC { get { return _pohlaserkridc; } set { _pohlaserkridc = value; OnPropertyChanged("PohLaserKridC");} }
    	private string _pohlaserkrid;
        public string PohLaserKrid { get { return _pohlaserkrid; } set { _pohlaserkrid = value; OnPropertyChanged("PohLaserKrid");} }
    	private string _nepohlaserkridc;
        public string NepohLaserKridC { get { return _nepohlaserkridc; } set { _nepohlaserkridc = value; OnPropertyChanged("NepohLaserKridC");} }
    	private string _nepohlaserkrid;
        public string NepohLaserKrid { get { return _nepohlaserkrid; } set { _nepohlaserkrid = value; OnPropertyChanged("NepohLaserKrid");} }
    	private string _klapackalaserkridc;
        public string KlapackaLaserKridC { get { return _klapackalaserkridc; } set { _klapackalaserkridc = value; OnPropertyChanged("KlapackaLaserKridC");} }
    	private string _klapackalaserkrid;
        public string KlapackaLaserKrid { get { return _klapackalaserkrid; } set { _klapackalaserkrid = value; OnPropertyChanged("KlapackaLaserKrid");} }
    	private string _okoplaserkridc;
        public string OkopLaserKridC { get { return _okoplaserkridc; } set { _okoplaserkridc = value; OnPropertyChanged("OkopLaserKridC");} }
    	private string _okoplaserkrid;
        public string OkopLaserKrid { get { return _okoplaserkrid; } set { _okoplaserkrid = value; OnPropertyChanged("OkopLaserKrid");} }
    	private string _ohybackakridc;
        public string OhybackaKridC { get { return _ohybackakridc; } set { _ohybackakridc = value; OnPropertyChanged("OhybackaKridC");} }
    	private string _ohybackakrid;
        public string OhybackaKrid { get { return _ohybackakrid; } set { _ohybackakrid = value; OnPropertyChanged("OhybackaKrid");} }
    	private string _pohohybackakridc;
        public string PohOhybackaKridC { get { return _pohohybackakridc; } set { _pohohybackakridc = value; OnPropertyChanged("PohOhybackaKridC");} }
    	private string _pohohybackakrid;
        public string PohOhybackaKrid { get { return _pohohybackakrid; } set { _pohohybackakrid = value; OnPropertyChanged("PohOhybackaKrid");} }
    	private string _nepohohybackakridc;
        public string NepohOhybackaKridC { get { return _nepohohybackakridc; } set { _nepohohybackakridc = value; OnPropertyChanged("NepohOhybackaKridC");} }
    	private string _nepohohybackakrid;
        public string NepohOhybackaKrid { get { return _nepohohybackakrid; } set { _nepohohybackakrid = value; OnPropertyChanged("NepohOhybackaKrid");} }
    	private string _klapackaohybackakridc;
        public string KlapackaOhybackaKridC { get { return _klapackaohybackakridc; } set { _klapackaohybackakridc = value; OnPropertyChanged("KlapackaOhybackaKridC");} }
    	private string _klapackaohybackakrid;
        public string KlapackaOhybackaKrid { get { return _klapackaohybackakrid; } set { _klapackaohybackakrid = value; OnPropertyChanged("KlapackaOhybackaKrid");} }
    	private string _bodovanikridc;
        public string BodovaniKridC { get { return _bodovanikridc; } set { _bodovanikridc = value; OnPropertyChanged("BodovaniKridC");} }
    	private string _bodovanikrid;
        public string BodovaniKrid { get { return _bodovanikrid; } set { _bodovanikrid = value; OnPropertyChanged("BodovaniKrid");} }
    	private string _splnenobodovanikridc;
        public string SplnenoBodovaniKridC { get { return _splnenobodovanikridc; } set { _splnenobodovanikridc = value; OnPropertyChanged("SplnenoBodovaniKridC");} }
    	private string _splnenobodovanikrid;
        public string SplnenoBodovaniKrid { get { return _splnenobodovanikrid; } set { _splnenobodovanikrid = value; OnPropertyChanged("SplnenoBodovaniKrid");} }
    	private string _thermacolkridc;
        public string ThermacolKridC { get { return _thermacolkridc; } set { _thermacolkridc = value; OnPropertyChanged("ThermacolKridC");} }
    	private string _thermacolkrid;
        public string ThermacolKrid { get { return _thermacolkrid; } set { _thermacolkrid = value; OnPropertyChanged("ThermacolKrid");} }
    	private string _narezthermacolkridc;
        public string NarezThermacolKridC { get { return _narezthermacolkridc; } set { _narezthermacolkridc = value; OnPropertyChanged("NarezThermacolKridC");} }
    	private string _narezthermacolkrid;
        public string NarezThermacolKrid { get { return _narezthermacolkrid; } set { _narezthermacolkrid = value; OnPropertyChanged("NarezThermacolKrid");} }
    	private string _lepenithermacolkridc;
        public string LepeniThermacolKridC { get { return _lepenithermacolkridc; } set { _lepenithermacolkridc = value; OnPropertyChanged("LepeniThermacolKridC");} }
    	private string _lepenithermacolkrid;
        public string LepeniThermacolKrid { get { return _lepenithermacolkrid; } set { _lepenithermacolkrid = value; OnPropertyChanged("LepeniThermacolKrid");} }
    	private string _cncthermacolkridc;
        public string CncThermacolKridC { get { return _cncthermacolkridc; } set { _cncthermacolkridc = value; OnPropertyChanged("CncThermacolKridC");} }
    	private string _cncthermacolkrid;
        public string CncThermacolKrid { get { return _cncthermacolkrid; } set { _cncthermacolkrid = value; OnPropertyChanged("CncThermacolKrid");} }
    	private string _lepenikridc;
        public string LepeniKridC { get { return _lepenikridc; } set { _lepenikridc = value; OnPropertyChanged("LepeniKridC");} }
    	private string _lepenikrid;
        public string LepeniKrid { get { return _lepenikrid; } set { _lepenikrid = value; OnPropertyChanged("LepeniKrid");} }
    	private string _splnenolepenikridc;
        public string SplnenoLepeniKridC { get { return _splnenolepenikridc; } set { _splnenolepenikridc = value; OnPropertyChanged("SplnenoLepeniKridC");} }
    	private string _splnenolepenikrid;
        public string SplnenoLepeniKrid { get { return _splnenolepenikrid; } set { _splnenolepenikrid = value; OnPropertyChanged("SplnenoLepeniKrid");} }
    	private string _strikarnakridc;
        public string StrikarnaKridC { get { return _strikarnakridc; } set { _strikarnakridc = value; OnPropertyChanged("StrikarnaKridC");} }
    	private string _strikarnakrid;
        public string StrikarnaKrid { get { return _strikarnakrid; } set { _strikarnakrid = value; OnPropertyChanged("StrikarnaKrid");} }
    	private string _splnenostrikarnakridc;
        public string SplnenoStrikarnaKridC { get { return _splnenostrikarnakridc; } set { _splnenostrikarnakridc = value; OnPropertyChanged("SplnenoStrikarnaKridC");} }
    	private string _splnenostrikarnakrid;
        public string SplnenoStrikarnaKrid { get { return _splnenostrikarnakrid; } set { _splnenostrikarnakrid = value; OnPropertyChanged("SplnenoStrikarnaKrid");} }
    	private string _rameckykridc;
        public string RameckyKridC { get { return _rameckykridc; } set { _rameckykridc = value; OnPropertyChanged("RameckyKridC");} }
    	private string _rameckykrid;
        public string RameckyKrid { get { return _rameckykrid; } set { _rameckykrid = value; OnPropertyChanged("RameckyKrid");} }
    	private string _narezrameckykridc;
        public string NarezRameckyKridC { get { return _narezrameckykridc; } set { _narezrameckykridc = value; OnPropertyChanged("NarezRameckyKridC");} }
    	private string _narezrameckykrid;
        public string NarezRameckyKrid { get { return _narezrameckykrid; } set { _narezrameckykrid = value; OnPropertyChanged("NarezRameckyKrid");} }
    	private string _frezrameckykridc;
        public string FrezRameckyKridC { get { return _frezrameckykridc; } set { _frezrameckykridc = value; OnPropertyChanged("FrezRameckyKridC");} }
    	private string _frezrameckykrid;
        public string FrezRameckyKrid { get { return _frezrameckykrid; } set { _frezrameckykrid = value; OnPropertyChanged("FrezRameckyKrid");} }
    	private string _svarrameckykridc;
        public string SvarRameckyKridC { get { return _svarrameckykridc; } set { _svarrameckykridc = value; OnPropertyChanged("SvarRameckyKridC");} }
    	private string _svarrameckykrid;
        public string SvarRameckyKrid { get { return _svarrameckykrid; } set { _svarrameckykrid = value; OnPropertyChanged("SvarRameckyKrid");} }
    	private string _strirameckykridc;
        public string StriRameckyKridC { get { return _strirameckykridc; } set { _strirameckykridc = value; OnPropertyChanged("StriRameckyKridC");} }
    	private string _strirameckykrid;
        public string StriRameckyKrid { get { return _strirameckykrid; } set { _strirameckykrid = value; OnPropertyChanged("StriRameckyKrid");} }
    	private string _kompletacekridc;
        public string KompletaceKridC { get { return _kompletacekridc; } set { _kompletacekridc = value; OnPropertyChanged("KompletaceKridC");} }
    	private string _kompletacekrid;
        public string KompletaceKrid { get { return _kompletacekrid; } set { _kompletacekrid = value; OnPropertyChanged("KompletaceKrid");} }
    	private string _splnenokompletacekridc;
        public string SplnenoKompletaceKridC { get { return _splnenokompletacekridc; } set { _splnenokompletacekridc = value; OnPropertyChanged("SplnenoKompletaceKridC");} }
    	private string _splnenokompletacekrid;
        public string SplnenoKompletaceKrid { get { return _splnenokompletacekrid; } set { _splnenokompletacekrid = value; OnPropertyChanged("SplnenoKompletaceKrid");} }
    	private string _skladkridc;
        public string SkladKridC { get { return _skladkridc; } set { _skladkridc = value; OnPropertyChanged("SkladKridC");} }
    	private string _skladkrid;
        public string SkladKrid { get { return _skladkrid; } set { _skladkrid = value; OnPropertyChanged("SkladKrid");} }
    	private string _plechskladkridc;
        public string PlechSkladKridC { get { return _plechskladkridc; } set { _plechskladkridc = value; OnPropertyChanged("PlechSkladKridC");} }
    	private string _plechskladkrid;
        public string PlechSkladKrid { get { return _plechskladkrid; } set { _plechskladkrid = value; OnPropertyChanged("PlechSkladKrid");} }
    	private string _kovaniskladkridc;
        public string KovaniSkladKridC { get { return _kovaniskladkridc; } set { _kovaniskladkridc = value; OnPropertyChanged("KovaniSkladKridC");} }
    	private string _kovaniskladkrid;
        public string KovaniSkladKrid { get { return _kovaniskladkrid; } set { _kovaniskladkrid = value; OnPropertyChanged("KovaniSkladKrid");} }
    	private string _barvaskladkridc;
        public string BarvaSkladKridC { get { return _barvaskladkridc; } set { _barvaskladkridc = value; OnPropertyChanged("BarvaSkladKridC");} }
    	private string _barvaskladkrid;
        public string BarvaSkladKrid { get { return _barvaskladkrid; } set { _barvaskladkrid = value; OnPropertyChanged("BarvaSkladKrid");} }
    	private string _skloskladkridc;
        public string SkloSkladKridC { get { return _skloskladkridc; } set { _skloskladkridc = value; OnPropertyChanged("SkloSkladKridC");} }
    	private string _skloskladkrid;
        public string SkloSkladKrid { get { return _skloskladkrid; } set { _skloskladkrid = value; OnPropertyChanged("SkloSkladKrid");} }
    	private string _pripravahlic;
        public string PripravaHliC { get { return _pripravahlic; } set { _pripravahlic = value; OnPropertyChanged("PripravaHliC");} }
    	private string _pripravahli;
        public string PripravaHli { get { return _pripravahli; } set { _pripravahli = value; OnPropertyChanged("PripravaHli");} }
    	private string _dokumentpripravahlic;
        public string DokumentPripravaHliC { get { return _dokumentpripravahlic; } set { _dokumentpripravahlic = value; OnPropertyChanged("DokumentPripravaHliC");} }
    	private string _dokumentpripravahli;
        public string DokumentPripravaHli { get { return _dokumentpripravahli; } set { _dokumentpripravahli = value; OnPropertyChanged("DokumentPripravaHli");} }
    	private string _indocapripravahlic;
        public string IndocaPripravaHliC { get { return _indocapripravahlic; } set { _indocapripravahlic = value; OnPropertyChanged("IndocaPripravaHliC");} }
    	private string _indocapripravahli;
        public string IndocaPripravaHli { get { return _indocapripravahli; } set { _indocapripravahli = value; OnPropertyChanged("IndocaPripravaHli");} }
    	private string _narezhlic;
        public string NarezHliC { get { return _narezhlic; } set { _narezhlic = value; OnPropertyChanged("NarezHliC");} }
    	private string _narezhli;
        public string NarezHli { get { return _narezhli; } set { _narezhli = value; OnPropertyChanged("NarezHli");} }
    	private string _profilnarezhlic;
        public string ProfilNarezHliC { get { return _profilnarezhlic; } set { _profilnarezhlic = value; OnPropertyChanged("ProfilNarezHliC");} }
    	private string _profilnarezhli;
        public string ProfilNarezHli { get { return _profilnarezhli; } set { _profilnarezhli = value; OnPropertyChanged("ProfilNarezHli");} }
    	private string _listynarezhlic;
        public string ListyNarezHliC { get { return _listynarezhlic; } set { _listynarezhlic = value; OnPropertyChanged("ListyNarezHliC");} }
    	private string _listynarezhli;
        public string ListyNarezHli { get { return _listynarezhli; } set { _listynarezhli = value; OnPropertyChanged("ListyNarezHli");} }
    	private string _cnchlic;
        public string CncHliC { get { return _cnchlic; } set { _cnchlic = value; OnPropertyChanged("CncHliC");} }
    	private string _cnchli;
        public string CncHli { get { return _cnchli; } set { _cnchli = value; OnPropertyChanged("CncHli");} }
    	private string _splnenocnchlic;
        public string SplnenoCncHliC { get { return _splnenocnchlic; } set { _splnenocnchlic = value; OnPropertyChanged("SplnenoCncHliC");} }
    	private string _splnenocnchli;
        public string SplnenoCncHli { get { return _splnenocnchli; } set { _splnenocnchli = value; OnPropertyChanged("SplnenoCncHli");} }
    	private string _frezahlic;
        public string FrezaHliC { get { return _frezahlic; } set { _frezahlic = value; OnPropertyChanged("FrezaHliC");} }
    	private string _frezahli;
        public string FrezaHli { get { return _frezahli; } set { _frezahli = value; OnPropertyChanged("FrezaHli");} }
    	private string _splnenofrezahlic;
        public string SplnenoFrezaHliC { get { return _splnenofrezahlic; } set { _splnenofrezahlic = value; OnPropertyChanged("SplnenoFrezaHliC");} }
    	private string _splnenofrezahli;
        public string SplnenoFrezaHli { get { return _splnenofrezahli; } set { _splnenofrezahli = value; OnPropertyChanged("SplnenoFrezaHli");} }
    	private string _priprava2hlic;
        public string Priprava2HliC { get { return _priprava2hlic; } set { _priprava2hlic = value; OnPropertyChanged("Priprava2HliC");} }
    	private string _priprava2hli;
        public string Priprava2Hli { get { return _priprava2hli; } set { _priprava2hli = value; OnPropertyChanged("Priprava2Hli");} }
    	private string _splnenopriprava2hlic;
        public string SplnenoPriprava2HliC { get { return _splnenopriprava2hlic; } set { _splnenopriprava2hlic = value; OnPropertyChanged("SplnenoPriprava2HliC");} }
    	private string _splnenopriprava2hli;
        public string SplnenoPriprava2Hli { get { return _splnenopriprava2hli; } set { _splnenopriprava2hli = value; OnPropertyChanged("SplnenoPriprava2Hli");} }
    	private string _strikarnahlic;
        public string StrikarnaHliC { get { return _strikarnahlic; } set { _strikarnahlic = value; OnPropertyChanged("StrikarnaHliC");} }
    	private string _strikarnahli;
        public string StrikarnaHli { get { return _strikarnahli; } set { _strikarnahli = value; OnPropertyChanged("StrikarnaHli");} }
    	private string _splnenostrikarnahlic;
        public string SplnenoStrikarnaHliC { get { return _splnenostrikarnahlic; } set { _splnenostrikarnahlic = value; OnPropertyChanged("SplnenoStrikarnaHliC");} }
    	private string _splnenostrikarnahli;
        public string SplnenoStrikarnaHli { get { return _splnenostrikarnahli; } set { _splnenostrikarnahli = value; OnPropertyChanged("SplnenoStrikarnaHli");} }
    	private string _kompletacehlic;
        public string KompletaceHliC { get { return _kompletacehlic; } set { _kompletacehlic = value; OnPropertyChanged("KompletaceHliC");} }
    	private string _kompletacehli;
        public string KompletaceHli { get { return _kompletacehli; } set { _kompletacehli = value; OnPropertyChanged("KompletaceHli");} }
    	private string _splnenokompletacehlic;
        public string SplnenoKompletaceHliC { get { return _splnenokompletacehlic; } set { _splnenokompletacehlic = value; OnPropertyChanged("SplnenoKompletaceHliC");} }
    	private string _splnenokompletacehli;
        public string SplnenoKompletaceHli { get { return _splnenokompletacehli; } set { _splnenokompletacehli = value; OnPropertyChanged("SplnenoKompletaceHli");} }
    	private string _skladhlic;
        public string SkladHliC { get { return _skladhlic; } set { _skladhlic = value; OnPropertyChanged("SkladHliC");} }
    	private string _skladhli;
        public string SkladHli { get { return _skladhli; } set { _skladhli = value; OnPropertyChanged("SkladHli");} }
    	private string _profilskladhlic;
        public string ProfilSkladHliC { get { return _profilskladhlic; } set { _profilskladhlic = value; OnPropertyChanged("ProfilSkladHliC");} }
    	private string _profilskladhli;
        public string ProfilSkladHli { get { return _profilskladhli; } set { _profilskladhli = value; OnPropertyChanged("ProfilSkladHli");} }
    	private string _barvaskladhlic;
        public string BarvaSkladHliC { get { return _barvaskladhlic; } set { _barvaskladhlic = value; OnPropertyChanged("BarvaSkladHliC");} }
    	private string _barvaskladhli;
        public string BarvaSkladHli { get { return _barvaskladhli; } set { _barvaskladhli = value; OnPropertyChanged("BarvaSkladHli");} }
    	private string _kovaniskladhlic;
        public string KovaniSkladHliC { get { return _kovaniskladhlic; } set { _kovaniskladhlic = value; OnPropertyChanged("KovaniSkladHliC");} }
    	private string _kovaniskladhli;
        public string KovaniSkladHli { get { return _kovaniskladhli; } set { _kovaniskladhli = value; OnPropertyChanged("KovaniSkladHli");} }
    	private string _skloskladhlic;
        public string SkloSkladHliC { get { return _skloskladhlic; } set { _skloskladhlic = value; OnPropertyChanged("SkloSkladHliC");} }
    	private string _skloskladhli;
        public string SkloSkladHli { get { return _skloskladhli; } set { _skloskladhli = value; OnPropertyChanged("SkloSkladHli");} }
    	private string _pozadovanycolor;
        public string PozadovanyColor { get { return _pozadovanycolor; } set { _pozadovanycolor = value; OnPropertyChanged("PozadovanyColor");} }
    	private Nullable<System.DateTime> _pozadovanydatum;
        public Nullable<System.DateTime> PozadovanyDatum { get { return _pozadovanydatum; } set { _pozadovanydatum = value; OnPropertyChanged("PozadovanyDatum");} }
    	private string _dokoncenicolor;
        public string DokonceniColor { get { return _dokoncenicolor; } set { _dokoncenicolor = value; OnPropertyChanged("DokonceniColor");} }
    	private Nullable<System.DateTime> _dokoncenidatum;
        public Nullable<System.DateTime> DokonceniDatum { get { return _dokoncenidatum; } set { _dokoncenidatum = value; OnPropertyChanged("DokonceniDatum");} }
    	private string _adresa;
        public string Adresa { get { return _adresa; } set { _adresa = value; OnPropertyChanged("Adresa");} }
    	private string _ulice;
        public string Ulice { get { return _ulice; } set { _ulice = value; OnPropertyChanged("Ulice");} }
    	private string _cislo;
        public string Cislo { get { return _cislo; } set { _cislo = value; OnPropertyChanged("Cislo");} }
    	private string _mesto;
        public string Mesto { get { return _mesto; } set { _mesto = value; OnPropertyChanged("Mesto");} }
    	private string _psc;
        public string PSC { get { return _psc; } set { _psc = value; OnPropertyChanged("PSC");} }
    	private string _plosnymaterial;
        public string PlosnyMaterial { get { return _plosnymaterial; } set { _plosnymaterial = value; OnPropertyChanged("PlosnyMaterial");} }
    	private string _poznamky;
        public string Poznamky { get { return _poznamky; } set { _poznamky = value; OnPropertyChanged("Poznamky");} }
    	private string _hotovobloky;
        public string HotovoBloky { get { return _hotovobloky; } set { _hotovobloky = value; OnPropertyChanged("HotovoBloky");} }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expedition> Expeditions { get; set; }
    }
}
