//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmonogram
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class User : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        private int _userid;
        public int UserId { get { return _userid; } set { _userid = value; OnPropertyChanged("UserId");} }
    	private Nullable<bool> _isadmin;
        public Nullable<bool> IsAdmin { get { return _isadmin; } set { _isadmin = value; OnPropertyChanged("IsAdmin");} }
    	private string _username;
        public string Username { get { return _username; } set { _username = value; OnPropertyChanged("Username");} }
    	private string _password;
        public string Password { get { return _password; } set { _password = value; OnPropertyChanged("Password");} }
    	private Nullable<bool> _presundoarchivu;
        public Nullable<bool> PresunDoArchivu { get { return _presundoarchivu; } set { _presundoarchivu = value; OnPropertyChanged("PresunDoArchivu");} }
    	private Nullable<bool> _presundoexpedice;
        public Nullable<bool> PresunDoExpedice { get { return _presundoexpedice; } set { _presundoexpedice = value; OnPropertyChanged("PresunDoExpedice");} }
    	private Nullable<bool> _presundovyroby;
        public Nullable<bool> PresunDoVyroby { get { return _presundovyroby; } set { _presundovyroby = value; OnPropertyChanged("PresunDoVyroby");} }
    	private Nullable<bool> _prepiscislozakazky;
        public Nullable<bool> PrepisCisloZakazky { get { return _prepiscislozakazky; } set { _prepiscislozakazky = value; OnPropertyChanged("PrepisCisloZakazky");} }
    	private Nullable<bool> _expedice;
        public Nullable<bool> Expedice { get { return _expedice; } set { _expedice = value; OnPropertyChanged("Expedice");} }
    	private Nullable<bool> _archiv;
        public Nullable<bool> Archiv { get { return _archiv; } set { _archiv = value; OnPropertyChanged("Archiv");} }
    	private Nullable<bool> _pristupdrevo;
        public Nullable<bool> PristupDrevo { get { return _pristupdrevo; } set { _pristupdrevo = value; OnPropertyChanged("PristupDrevo");} }
    	private Nullable<bool> _pristupocel;
        public Nullable<bool> PristupOcel { get { return _pristupocel; } set { _pristupocel = value; OnPropertyChanged("PristupOcel");} }
    	private Nullable<bool> _pristuphlinik;
        public Nullable<bool> PristupHlinik { get { return _pristuphlinik; } set { _pristuphlinik = value; OnPropertyChanged("PristupHlinik");} }
    	private Nullable<bool> _obchod;
        public Nullable<bool> Obchod { get { return _obchod; } set { _obchod = value; OnPropertyChanged("Obchod");} }
    	private Nullable<bool> _priprava;
        public Nullable<bool> Priprava { get { return _priprava; } set { _priprava = value; OnPropertyChanged("Priprava");} }
    	private Nullable<bool> _oblozky;
        public Nullable<bool> Oblozky { get { return _oblozky; } set { _oblozky = value; OnPropertyChanged("Oblozky");} }
    	private Nullable<bool> _stredove;
        public Nullable<bool> Stredove { get { return _stredove; } set { _stredove = value; OnPropertyChanged("Stredove");} }
    	private Nullable<bool> _ramecek;
        public Nullable<bool> Ramecek { get { return _ramecek; } set { _ramecek = value; OnPropertyChanged("Ramecek");} }
    	private Nullable<bool> _klapacka;
        public Nullable<bool> Klapacka { get { return _klapacka; } set { _klapacka = value; OnPropertyChanged("Klapacka");} }
    	private Nullable<bool> _posuv;
        public Nullable<bool> Posuv { get { return _posuv; } set { _posuv = value; OnPropertyChanged("Posuv");} }
    	private Nullable<bool> _dvere;
        public Nullable<bool> Dvere { get { return _dvere; } set { _dvere = value; OnPropertyChanged("Dvere");} }
    	private Nullable<bool> _dokonceni;
        public Nullable<bool> Dokonceni { get { return _dokonceni; } set { _dokonceni = value; OnPropertyChanged("Dokonceni");} }
    	private Nullable<bool> _kompletace;
        public Nullable<bool> Kompletace { get { return _kompletace; } set { _kompletace = value; OnPropertyChanged("Kompletace");} }
    	private Nullable<bool> _sklad;
        public Nullable<bool> Sklad { get { return _sklad; } set { _sklad = value; OnPropertyChanged("Sklad");} }
    	private Nullable<bool> _pripravarvyroby;
        public Nullable<bool> PripravarVyroby { get { return _pripravarvyroby; } set { _pripravarvyroby = value; OnPropertyChanged("PripravarVyroby");} }
    }
}
